name: Build Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [android, web]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache Flutter dependencies to speed up builds
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build APK and AAB for Android
      - name: Build APK and App Bundle for Android
        if: matrix.platform == 'android'
        run: |
          flutter build apk --release
          flutter build appbundle --release

      # Sign the AAB
      - name: Sign AAB
        if: matrix.platform == 'android'
        uses: r0adkll/sign-android-release@v1
        with:
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          releaseDirectory: build/app/outputs/bundle/release

      # Build for Web
      - name: Build Web
        if: matrix.platform == 'web'
        run: flutter build web --release --web-renderer html

      # Upload Signed APK
      - name: Upload Signed APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Upload Signed AAB
      - name: Upload Signed AAB
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab

      # Upload Web Build
      - name: Upload Web Build
        if: matrix.platform == 'web'
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
